
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Jacob-LJ/JASpecs.git'

use_frameworks!

target 'JAButton_Example' do
  pod 'JAButton', :path => '../'

  target 'JAButton_Tests' do
    inherit! :search_paths

    
  end
end
